export type { I2CPortNumber } from './i2c-port-number.js';
export { isI2CPortNumber } from './i2c-port-number.js';
export type { I2CSlaveAddress } from './i2c-slave-address.js';
export { isI2CSlaveAddress } from './i2c-slave-address.js';
export type { I2CRegisterNumber } from './i2c-register-number.js';
export { isI2CRegisterNumber } from './i2c-register-number.js';
export type { I2CByte, I2CBytesLength, I2CWord } from './i2c-byte.js';
export { isI2CByte, isI2CBytesLength, isI2CWord } from './i2c-byte.js';
export type { I2CSlaveDevice } from './i2c-slave-device.js';
export type { I2CPort } from './i2c-port.js';
export type { I2CAccess, I2CPortMap } from './i2c-access.js';
